<?php
Route::group(['prefix'=>'admin','namespace'=>'Admin'],function(){
    //登录页
    Route::get('login','LoginController@login');
    //处理登录
    Route::post('dologin','LoginController@doLogin');
    //加密算法
    Route::get('jiami','LoginController@jiami');
    //验证码路由
    Route::get('code','LoginController@code');
});
Route::get('code/captcha/{tmp}','Admin\LoginController@captcha');
Route::group(['prefix'=>'admin','namespace'=>'Admin','middleware'=>'isLogin'],function(){
    //首页
    Route::get('index','LoginController@index');
    //欢迎页
    Route::get('welcome','LoginController@welcome');
    //退出登录
    Route::get('logout','LoginController@logout');
    Route::get('user/del','UserController@delAll');
    //用户模块
    Route::resource('user','UserController');
});

